import { useState } from "react";
import { Copy, Printer, X } from "lucide-react";

import DocumentLink from "./DocumentLink";
import type { Appeal } from "../types/dental";

/**
 * G-05 — the appeal packet, assembled.
 *
 * ⚠ EVERY SECTION IS READ FROM THE API. Nothing here composes a
 * clinical argument: the grounds are the engine's `appeal_strategy`,
 * the citation is a catalogue row, the evidence is the documents on
 * file, and the letter is dental-os's own draft — which is itself
 * assembled from catalogue rows, not generated. dental-simulator
 * Gap #3 (no appeal generator) is still open and this does not close
 * it; it renders what exists and says DRAFT throughout.
 *
 * Two fields the brief expected do not exist. There is no
 * `grounds_for_appeal` — the field is `appeal_strategy`. And for a
 * PENDED pre-D, `denial_reason_code` and `denial_reason_text` are null,
 * because no denial has been issued yet. The denial section says so
 * rather than printing an empty label a reviewer would read as an
 * omission.
 */
export default function AppealPacket({
  appeal,
  practiceName = "Suwanee Smiles Dental",
  providerName,
  onClose,
}: {
  appeal: Appeal;
  practiceName?: string;
  providerName?: string;
  onClose: () => void;
}) {
  const [copied, setCopied] = useState(false);

  const citation = appeal.citations[0];
  const documents = appeal.evidence_list.filter(
    (e) => e.document_type !== "PRED_LETTER",
  );

  function packetText(): string {
    return [
      `APPEAL — ${appeal.patient_name}`,
      `${appeal.payer_id} · Pre-D ${appeal.pred_number ?? "—"}`,
      "Generated by Accord Dental · DRAFT",
      "",
      "PATIENT & PROVIDER",
      `  Patient: ${appeal.patient_name}`,
      `  Provider: ${providerName ?? "—"}`,
      `  Practice: ${practiceName}`,
      "",
      "DETERMINATION",
      `  Decision: ${appeal.decision}`,
      `  Reason code: ${appeal.denial_reason_code ?? "not issued — pre-D is pended"}`,
      appeal.denial_reason_text ? `  Reason: ${appeal.denial_reason_text}` : "",
      "",
      "GROUNDS FOR APPEAL",
      `  ${appeal.appeal_strategy ?? "—"}`,
      citation ? `  Citation: ${citation.source} §${citation.section}` : "",
      "",
      "SUPPORTING EVIDENCE",
      ...documents.map(
        (d) =>
          `  [x] ${d.document_type} — ${Math.round((d.confidence ?? 0) * 100)}% confidence`,
      ),
      ...appeal.missing_evidence.map((m) => `  [ ] ${m}`),
      "",
      "DRAFT LETTER",
      appeal.appeal_letter_text ?? "—",
    ]
      .filter((l) => l !== "")
      .join("\n");
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(packetText());
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch {
      window.prompt("Copy the packet below:", packetText());
    }
  }

  const Section = ({
    n,
    title,
    children,
  }: {
    n: number;
    title: string;
    children: React.ReactNode;
  }) => (
    <section className="border-t border-gray-200 pt-3">
      <h3 className="text-[10.5px] font-semibold uppercase tracking-wide text-gray-500">
        {n}. {title}
      </h3>
      <div className="mt-1.5 text-[12.5px] leading-relaxed text-gray-700">
        {children}
      </div>
    </section>
  );

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/50 sm:items-center sm:p-4"
      onClick={onClose}
      role="presentation"
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="packet-title"
        onClick={(e) => e.stopPropagation()}
        className="relative min-h-full w-full max-w-2xl bg-white p-5 shadow-xl sm:my-0 sm:min-h-0 sm:rounded-2xl sm:p-6"
      >
        <button
          type="button"
          onClick={onClose}
          aria-label="Close"
          className="absolute right-3 top-3 rounded-lg p-2.5 text-gray-500 hover:bg-gray-100 print:hidden"
        >
          <X size={20} />
        </button>

        <div className="print-only-packet">
          <header>
            <h2
              id="packet-title"
              className="text-[18px] font-semibold text-gray-900"
            >
              Appeal — {appeal.patient_name}
            </h2>
            <p className="mt-0.5 text-[12px] text-gray-500">
              {appeal.payer_id.replace(/_/g, " ")} · Pre-D{" "}
              {appeal.pred_number ?? "—"}
            </p>
            <p className="mt-1 inline-block rounded bg-accord-amber-50 px-2 py-0.5 text-[10.5px] font-semibold uppercase tracking-wide text-accord-amber-900">
              Generated by Accord Dental · Draft
            </p>
          </header>

          <div className="mt-4 space-y-3">
            <Section n={1} title="Patient & provider">
              <p>Patient: {appeal.patient_name}</p>
              {providerName && <p>Provider: {providerName}</p>}
              <p>Practice: {practiceName}</p>
            </Section>

            <Section n={2} title="Determination">
              <p>
                Decision:{" "}
                <span className="font-medium capitalize">{appeal.decision}</span>
              </p>
              <p>
                Reason code:{" "}
                {appeal.denial_reason_code ?? (
                  <span className="text-gray-500">
                    none issued — this pre-D is pended, not denied
                  </span>
                )}
              </p>
              {appeal.denial_reason_text && <p>{appeal.denial_reason_text}</p>}
            </Section>

            <Section n={3} title="Grounds for appeal">
              <p>{appeal.appeal_strategy ?? "—"}</p>
              {citation && (
                <p className="mt-1.5 text-[11.5px] italic text-accord-green-700">
                  {citation.source}
                  {citation.section ? ` §${citation.section}` : ""}
                </p>
              )}
            </Section>

            <Section n={4} title="Supporting evidence">
              <ul className="space-y-1">
                {documents.map((d) => (
                  <li key={d.document_type} className="flex gap-2">
                    <span className="text-accord-green-700">✓</span>
                    <span>
                      {d.document_type.replace(/_/g, " ")} —{" "}
                      {Math.round((d.confidence ?? 0) * 100)}% confidence
                      <DocumentLink
                        predRequestId={appeal.pred_request_id}
                        evidenceId={d.evidence_id}
                        hasDocument={d.has_document}
                        className="ml-2 print:hidden"
                      />
                    </span>
                  </li>
                ))}
                {appeal.missing_evidence.map((m) => (
                  <li key={m} className="flex gap-2 text-gray-500">
                    <span className="text-red-500">✗</span>
                    <span>{m}</span>
                  </li>
                ))}
              </ul>
            </Section>

            <Section n={5} title="Draft letter">
              <pre className="max-h-56 overflow-y-auto whitespace-pre-wrap rounded-lg border border-gray-200 bg-gray-50 p-3 font-sans text-[11.5px] leading-relaxed text-gray-700">
                {appeal.appeal_letter_text ?? "No draft letter available."}
              </pre>
              <p className="mt-2 text-[11px] text-accord-amber-900">
                This letter is a packet skeleton assembled from catalogue rows.
                Review and sign before submission.
              </p>
            </Section>
          </div>
        </div>

        <div className="mt-5 flex flex-wrap items-center gap-2 border-t border-gray-200 pt-4 print:hidden">
          <button
            type="button"
            onClick={copy}
            className="inline-flex items-center gap-1.5 rounded-lg bg-accord-green-900 px-3.5 py-2 text-[12.5px] font-semibold text-white transition hover:bg-accord-green-700"
          >
            <Copy size={14} />
            Copy packet
          </button>
          <button
            type="button"
            onClick={() => window.print()}
            className="inline-flex items-center gap-1.5 rounded-lg border border-gray-300 px-3.5 py-2 text-[12.5px] font-medium text-gray-700 transition hover:bg-gray-50"
          >
            <Printer size={14} />
            Print packet
          </button>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg px-3.5 py-2 text-[12.5px] font-medium text-gray-500 hover:bg-gray-50"
          >
            Close
          </button>
          {copied && (
            <span className="text-[12px] font-medium text-accord-green-700">
              Packet copied to clipboard
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
