-- 004 — the dentist's half of a pre-D: narrative, justification,
-- document requests, and the attestation that signs it off.
--
-- Follows 003 exactly: dental-os's own tables (CONTEXT.md RULE 15),
-- tenant_id on every row, ENABLE + FORCE ROW LEVEL SECURITY, USING and
-- WITH CHECK spelled out, and SELECT/INSERT/UPDATE granted to
-- dental_app because all four endpoints upsert.
--
-- Remember the RLS trap these protect against: a query that forgets
-- app.tenant_id returns zero rows and NO ERROR, which reads as "this
-- dentist has written nothing" rather than as a bug.

-- ── The narrative a dentist writes to support the case ─────────────
--
-- One live narrative per pre-D. Edits overwrite, and updated_at moves.
-- If a version history is ever needed this becomes append-only with an
-- is_current flag, the way persona_bundles already works — but a
-- dentist rewriting their own sentence before submitting is not an
-- audit event, and pretending otherwise fills the table with drafts.
CREATE TABLE IF NOT EXISTS clinical_narratives (
  narrative_id    TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  tenant_id       TEXT NOT NULL,
  pred_request_id TEXT NOT NULL,
  narrative_text  TEXT NOT NULL,
  -- 'draft'   generated by the engine, untouched by a human
  -- 'edited'  a dentist changed the generated text
  -- 'authored' a dentist wrote it from scratch
  source          TEXT NOT NULL DEFAULT 'edited',
  written_by      TEXT NOT NULL,          -- users.user_id
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS clinical_narratives_unique
  ON clinical_narratives(tenant_id, pred_request_id);


-- ── Why a criterion the engine could not confirm is met anyway ─────
--
-- Keyed on the SIGNAL, not the pre-D: a case can have several
-- unconfirmed criteria and each needs its own reasoning. This is the
-- dentist overriding the model with clinical judgement, so it records
-- who and when and never deletes.
CREATE TABLE IF NOT EXISTS clinical_justifications (
  justification_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  tenant_id        TEXT NOT NULL,
  pred_request_id  TEXT NOT NULL,
  signal_code      TEXT NOT NULL,
  justification    TEXT NOT NULL,
  justified_by     TEXT NOT NULL,         -- users.user_id
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS clinical_justifications_unique
  ON clinical_justifications(tenant_id, pred_request_id, signal_code);


-- ── "Front desk, please get me the x-ray" ──────────────────────────
--
-- One row per document asked for. NOT unique per (pre-D, document):
-- asking twice is a real event — the second ask is the chase — and
-- collapsing them would erase the fact that nobody answered the first.
CREATE TABLE IF NOT EXISTS document_requests (
  request_id      TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  tenant_id       TEXT NOT NULL,
  pred_request_id TEXT NOT NULL,
  document_type   TEXT NOT NULL,          -- XRAY_PA / PERIO_CHART / ...
  signal_code     TEXT,                   -- the gap that prompted it
  requested_from  TEXT NOT NULL DEFAULT 'front_desk',
  requested_by    TEXT NOT NULL,          -- users.user_id
  note            TEXT,
  status          TEXT NOT NULL DEFAULT 'open',  -- open/received/cancelled
  requested_at    TIMESTAMPTZ DEFAULT NOW(),
  resolved_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS document_requests_tenant_pred
  ON document_requests(tenant_id, pred_request_id, status);


-- ── The signature ──────────────────────────────────────────────────
--
-- A dentist stating the clinical record supports what is being billed.
-- APPEND-ONLY BY INTENT: no unique index and no upsert path. Every
-- attestation is a separate act by a named person at a named time, and
-- overwriting the previous one would destroy the only evidence of who
-- signed what. Read the latest by attested_at.
CREATE TABLE IF NOT EXISTS clinical_attestations (
  attestation_id  TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  tenant_id       TEXT NOT NULL,
  pred_request_id TEXT NOT NULL,
  attested_by     TEXT NOT NULL,          -- users.user_id, from the TOKEN
  attested_at     TIMESTAMPTZ DEFAULT NOW(),
  -- What was true at the moment of signing, so a later edit to the
  -- narrative cannot silently change what the dentist attested to.
  narrative_text  TEXT,
  statement       TEXT NOT NULL,
  submission_id   TEXT
);

CREATE INDEX IF NOT EXISTS clinical_attestations_tenant_pred
  ON clinical_attestations(tenant_id, pred_request_id, attested_at DESC);


-- ── RLS ────────────────────────────────────────────────────────────

ALTER TABLE clinical_narratives ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical_narratives FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS clinical_narratives_tenant ON clinical_narratives;
CREATE POLICY clinical_narratives_tenant ON clinical_narratives
  USING (tenant_id = current_setting('app.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

ALTER TABLE clinical_justifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical_justifications FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS clinical_justifications_tenant ON clinical_justifications;
CREATE POLICY clinical_justifications_tenant ON clinical_justifications
  USING (tenant_id = current_setting('app.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

ALTER TABLE document_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_requests FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS document_requests_tenant ON document_requests;
CREATE POLICY document_requests_tenant ON document_requests
  USING (tenant_id = current_setting('app.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

ALTER TABLE clinical_attestations ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical_attestations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS clinical_attestations_tenant ON clinical_attestations;
CREATE POLICY clinical_attestations_tenant ON clinical_attestations
  USING (tenant_id = current_setting('app.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

GRANT SELECT, INSERT, UPDATE ON clinical_narratives     TO dental_app;
GRANT SELECT, INSERT, UPDATE ON clinical_justifications TO dental_app;
GRANT SELECT, INSERT, UPDATE ON document_requests       TO dental_app;
-- No UPDATE on attestations: they are append-only. A row that can be
-- updated is not a signature.
GRANT SELECT, INSERT ON clinical_attestations TO dental_app;
