"""Regenerate tests/fixtures/*.sql from RDS.

Run when the corpus moves. The output is COMMITTED so the API suite is
offline and deterministic — a test run must not depend on AWS
credentials, a VPN, or whatever state production happens to be in.

    python scripts/refresh_test_fixture.py

── WHY pg_dump RUNS IN A CONTAINER ──────────────────────────────────
This machine has no psql or pg_dump on PATH, and the API suite already
needs a local Postgres container. Rather than make everyone install
client tools, the dump runs inside that container, which can reach RDS.

── WHAT IS AND IS NOT INCLUDED ──────────────────────────────────────
  dental (simulator)   EVERYTHING. 0.9 MB. It is the corpus the engine
                       reasons over and the tests need all of it.

  dental_os            Schema in full, data for everything EXCEPT:
      persona_bundles    3.9 MB on disk, ~25 MB as SQL — JSONB expands
      decision_outputs   badly. Only the is_current bundles for the
      pred_audit_log     handful of pre-Ds the tests touch are kept.

  users                EXCLUDED DELIBERATELY. Dumping it would commit
                       production auth rows and their bcrypt hashes.
                       conftest creates its own six accounts instead.
"""
from __future__ import annotations

import asyncio
import os
import pathlib
import subprocess
import sys

import asyncpg

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "tests" / "fixtures"
CONTAINER = os.environ.get("PG_CONTAINER", "dental-postgres")
RDS = "dental-postgres.c2feioes4hil.us-east-1.rds.amazonaws.com"

# Every pre-D an API test touches. Bundles are kept for these only.
TEST_PREDS = (
    "PRED-SIM-DA-A01",  # pended, bundling, the reference case
    "PRED-SIM-DA-B01",  # denied + appeal overturned
    "PRED-SIM-DA-B04",  # denied + appeal pending
    "PRED-SIM-DA-B05",  # denied + appeal upheld
    "PRED-SIM-DA-D04",  # engine-ready, no documentation gaps
    "PRED-SIM-DA-U01",  # cleared by the engine
    "PRED-SIM-DA-U02",  # missing radiograph
    # No Tampa pre-D: the cross-tenant tests assert 404, and
    # assert_tenant_allowed fires before any bundle is read, so its
    # bundle would be ~350 KB of fixture nothing looks at.
)


def _ssm(name: str) -> str:
    return subprocess.run(
        ["aws", "ssm", "get-parameter", "--name", name, "--with-decryption",
         "--profile", "dental", "--query", "Parameter.Value", "--output", "text"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()


def _dump(db: str, extra: list[str]) -> str:
    cmd = [
        "docker", "exec", "-e", f"PGPASSWORD={_ssm('/dental/db/password')}",
        CONTAINER, "pg_dump", "-h", RDS, "-U", "dental_admin", "-d", db,
        "--no-owner", "--no-acl", *extra,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        raise SystemExit(f"pg_dump {db} failed:\n{r.stderr[-2000:]}")
    return r.stdout


def _literal(v) -> str:
    """One value as SQL. Enough types for these two tables, and a loud
    failure for anything else rather than a silently wrong dump."""
    import datetime
    import decimal
    import json
    import uuid

    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float, decimal.Decimal)):
        return str(v)
    if isinstance(v, (dict, list)):
        return "'" + json.dumps(v).replace("'", "''") + "'::jsonb"
    if isinstance(v, (datetime.datetime, datetime.date, uuid.UUID)):
        return "'" + str(v) + "'"
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    raise TypeError(f"no SQL literal for {type(v)}")


async def _subset_inserts() -> str:
    """persona_bundles + decision_outputs, for the test pre-Ds only."""
    pw = _ssm("/dental/db/password")
    dsn = f"postgresql://dental_admin:{pw}@{RDS}:5432/dental_os"
    conn = await asyncpg.connect(dsn)
    try:
        out: list[str] = [
            "-- Generated by scripts/refresh_test_fixture.py.",
            "-- Only the pre-Ds the API suite touches, only current bundles.",
        ]
        bundles = await conn.fetch(
            "SELECT * FROM persona_bundles "
            "WHERE pred_request_id = ANY($1::text[]) AND is_current",
            list(TEST_PREDS),
        )
        ids = [b["bundle_id"] for b in bundles]
        outputs = await conn.fetch(
            "SELECT * FROM decision_outputs WHERE bundle_id = ANY($1::uuid[])",
            ids,
        ) if ids else []
        for table, rows in (("persona_bundles", bundles),
                            ("decision_outputs", outputs)):
            for r in rows:
                cols = ", ".join(r.keys())
                vals = ", ".join(_literal(v) for v in r.values())
                out.append(f"INSERT INTO {table} ({cols}) VALUES ({vals});")
        print(f"    {len(bundles)} bundles, {len(outputs)} outputs")
        return "\n".join(out) + "\n"
    finally:
        await conn.close()


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)

    sim = _dump("dental", [])
    (OUT / "dental.sql").write_text(sim, encoding="utf-8")
    print(f"  dental.sql      {len(sim)/1048576:.2f} MB")

    # Schema + the small tables. users excluded: see the module docstring.
    core = _dump("dental_os", [
        "--exclude-table-data=persona_bundles",
        "--exclude-table-data=decision_outputs",
        "--exclude-table-data=pred_audit_log",
        "--exclude-table-data=users",
    ])
    (OUT / "dental_os.sql").write_text(core, encoding="utf-8")
    print(f"  dental_os.sql   {len(core)/1048576:.2f} MB")

    # ⚠ NOT pg_dump. It has no --where, so a row filter is not
    # expressible — and dumping these two whole is the 25 MB this
    # function exists to avoid. asyncpg with a WHERE clause and
    # hand-built INSERTs is the smaller, clearer tool.
    both = asyncio.run(_subset_inserts())
    (OUT / "dental_os_bundles.sql").write_text(both, encoding="utf-8")
    print(f"  bundles.sql     {len(both)/1048576:.2f} MB")

    total = sum((OUT / f).stat().st_size for f in
                ("dental.sql", "dental_os.sql", "dental_os_bundles.sql"))
    print(f"  TOTAL           {total/1048576:.2f} MB")
    if total > 4 * 1048576:
        print("  ⚠ over 4 MB — trim TEST_PREDS before committing this.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
